"""Adding name field

Revision ID: 02c256ce2fe1
Revises: 5bb28a49d46e
Create Date: 2022-02-11 11:57:59.651371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c256ce2fe1'
down_revision = '5bb28a49d46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'name')
    # ### end Alembic commands ###
